## Estudio huracán María

Calcular la correlación de dos variables: velocidad en nudos y presión atmosférica

In [1]:
import numpy as np
import pandas as pd

In [2]:
path = "../practicas/mat_plot_lib/huracan_maria.csv"

In [6]:
dtHuracan = pd.read_csv(path, sep=';')
dtHuracan.head()

FECHA       HORA  LATITUD  LONGITUD  NUDOS  PRESION
0  sep-16  15:00 GMT     12.2     -50.5     35     1008
1  sep-16  18:00 GMT     11.9     -51.6     35     1006
2  sep-16  21:00 GMT     12.3     -52.6     50     1002
3  sep-17  00:00 GMT     12.4     -53.0     50     1002
4  sep-17  03:00 GMT     12.5     -53.7     50     1002

In [4]:
dtHuracan.shape

(120, 6)

In [12]:
nudos = dtHuracan['NUDOS'].values
presion = dtHuracan['PRESION'].values
t = np.corrcoef(nudos, presion)
t


array([[ 1.        , -0.95481815],
       [-0.95481815,  1.        ]])

In [13]:
corr = round(t[0,1]*100, 4)
corr

-95.4818

In [14]:
velMax = np.max(nudos)
velMax

175

In [15]:
ind_max = np.argmax(nudos)
ind_max

37

In [16]:
dtHuracan.iloc[ind_max]

FECHA          sep-19
HORA        23:00 GMT
LATITUD          16.9
LONGITUD        -64.1
NUDOS             175
PRESION           909
Name: 37, dtype: object

In [18]:
np.unique(dtHuracan.NUDOS)

array([ 35,  50,  60,  65,  70,  75,  80,  85,  90, 105, 110, 115, 120,
       125, 130, 140, 145, 150, 155, 160, 165, 175])

In [22]:
np.unique([1.401,1.4,1.4,2.5,2.5,3.1,5,6,7])

array([1.4  , 1.401, 2.5  , 3.1  , 5.   , 6.   , 7.   ])