## Pruebas con numpy

In [4]:
import numpy as np
from datetime import datetime

np.__version__

'1.21.5'

In [2]:
%%timeit
my_arr = np.arange(1000000)
for _ in range(10): my_arr2 = my_arr * 2

8.94 ms ± 40.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
%%timeit
my_list = list(range(1000000))
for _ in range(10): my_list2 = [x*2 for x in my_list]

479 ms ± 1.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
t1 = datetime.now()
my_arr = np.arange(1000000)
for _ in range(10): my_arr2 = my_arr * 2
t2 = datetime.now()
t2-t1

datetime.timedelta(microseconds=14667)

t1 = datetime.now()
my_list = list(range(1000000))
for _ in range(10): my_list2 = [x*2 for x in my_list]
t2 = datetime.now()
t2-t1

### Construir arrays con numpy

In [9]:
data = np.random.randn(2,3,4)
data

array([[[-0.38016491, -0.42731928,  0.19877525, -0.57623428],
        [-1.06066637, -0.48526792, -0.48093623,  2.63994395],
        [ 1.80177194,  1.26439429,  0.29843198,  0.23002593]],

       [[ 1.52080981,  0.63803906,  0.79321789,  1.94633251],
        [-0.51566559,  1.50841548,  0.45856443,  1.41414238],
        [-0.96838849, -1.47176638, -1.15822834, -0.61739821]]])

In [13]:
L = [1,5,6,7,8]
data = np.array(L)
data, type(data)

(array([1, 5, 6, 7, 8]), numpy.ndarray)

In [14]:
data = np.array(set(L))
data, type(data)

(array({1, 5, 6, 7, 8}, dtype=object), numpy.ndarray)

In [15]:
data = np.array([1,2,4.5,7])
data, data.dtype

(array([1. , 2. , 4.5, 7. ]), dtype('float64'))

In [17]:
data = np.array([1,2,4.5,7+2j])
data, data.dtype

(array([1. +0.j, 2. +0.j, 4.5+0.j, 7. +2.j]), dtype('complex128'))

In [19]:
data = np.array(["1","2","4","7"],dtype=np.int16)
data, data.dtype

(array([1, 2, 4, 7], dtype=int16), dtype('int16'))

In [20]:
data = np.array(["1","2","4","7"],dtype="i2") # Entero de 2 bytes
data, data.dtype

(array([1, 2, 4, 7], dtype=int16), dtype('int16'))

In [21]:
data.shape

(4,)

In [24]:
# Devuelve una copia
data2 = data.astype(np.float32)
data2

array([1., 2., 4., 7.], dtype=float32)

In [25]:
data.dtype

dtype('int16')

In [28]:
a = np.arange(0,50,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [29]:
b = np.empty((2,5))
b

array([[6.91704265e-310, 1.03392920e-316, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 2.34895330e-316, 1.63041663e-322,
        6.91704265e-310, 8.77163357e-317]])

In [31]:
c = np.zeros((3,4,5))
c[0][2][1]=100 # pagina, fila, columna
c

array([[[  0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.],
        [  0., 100.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.]],

       [[  0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.]],

       [[  0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.]]])

In [35]:
m = np.arange(16).reshape(2,8) 
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [36]:
m = np.arange(16).reshape(4,-1) 
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
m.fill(5)
m

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [38]:
print(m.nbytes)

128


In [39]:
m = m.astype(np.float32)
m.fill(5.5)
m

array([[5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5],
       [5.5, 5.5, 5.5, 5.5]], dtype=float32)

In [40]:
ceros = np.zeros_like(m)
ceros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [41]:
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Operaciones con vectores

In [44]:
a = np.random.randint(10,40,10)
b = np.random.randint(5,30,10)

In [45]:
a

array([21, 18, 27, 13, 21, 13, 20, 27, 12, 19])

In [46]:
b

array([15, 21, 17, 15, 15, 20, 10, 24, 11, 12])

In [47]:
a + 5

array([26, 23, 32, 18, 26, 18, 25, 32, 17, 24])

In [48]:
a

array([21, 18, 27, 13, 21, 13, 20, 27, 12, 19])

In [49]:
r = (a+b) * 10
r

array([360, 390, 440, 280, 360, 330, 300, 510, 230, 310])

Producto de 2 matrices

In [54]:
m1 = np.random.randint(10,40,(4,5))
m2 = np.random.randint(10,40,(5,4))
print(m1)
print()
print(m2)

[[20 16 26 16 24]
 [17 27 22 34 19]
 [17 21 30 26 13]
 [36 25 11 15 31]]

[[25 23 36 36]
 [10 34 34 11]
 [17 39 28 17]
 [18 23 28 22]
 [12 19 30 12]]


In [55]:
r = m1 @ m2
r

array([[1678, 2842, 3160, 1978],
       [1909, 3310, 3668, 2259],
       [1769, 3120, 3284, 2081],
       [1979, 3041, 3804, 2460]])

In [57]:
m1 = np.random.randint(10,40,15)
m1

array([17, 29, 38, 15, 36, 30, 33, 13, 15, 10, 39, 23, 16, 35, 33])

In [58]:
# Que no pasen de 30
m1[m1 > 30]=30
m1

array([17, 29, 30, 15, 30, 30, 30, 13, 15, 10, 30, 23, 16, 30, 30])

In [60]:
# Rangos
m1[(m1 >= 10) & (m1 <= 25)]

array([17, 15, 13, 15, 10, 23, 16])

In [61]:
m1[(m1 >= 10) & (m1 <= 25)]=-1
m1

array([-1, 29, 30, -1, 30, 30, 30, -1, -1, -1, 30, -1, -1, 30, 30])

In [62]:
m1 = np.random.randint(10,40,15)
m1

array([29, 12, 27, 28, 38, 22, 24, 23, 33, 20, 37, 28, 32, 37, 38])

In [63]:
m1[(m1 < 15) | (m1 > 25)]=0
m1

array([ 0,  0,  0,  0,  0, 22, 24, 23,  0, 20,  0,  0,  0,  0,  0])

In [66]:
m1 = np.random.randint(10,40,(4,5))
m2 = np.random.randint(10,40,(4,5))
print(m1)
print()
print(m2)

[[35 37 37 39 21]
 [11 36 12 21 17]
 [35 21 25 35 38]
 [34 33 36 35 22]]

[[21 22 25 10 22]
 [21 31 14 10 22]
 [22 27 25 10 26]
 [22 24 17 35 32]]


In [67]:
m1 > m2

array([[ True,  True,  True,  True, False],
       [False,  True, False,  True, False],
       [ True, False, False,  True,  True],
       [ True,  True,  True, False, False]])

In [68]:
m = np.arange(25).reshape(5,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
m[1:-1,1:-1]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [71]:
m = np.arange(5)
L = list(m)
L

[0, 1, 2, 3, 4]

In [73]:
m = np.arange(16).reshape(4,-1)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
m[[True,False,False,True]]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [75]:
m[[1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
arr = np.array(['A','B','B','A'])
m[arr=='A']

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [77]:
arr=='A'

array([ True, False, False,  True])

In [78]:
m.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [81]:
m = m.astype(np.float32)
m[0][0]=1.5
m**-1

array([[0.6666667 , 1.        , 0.5       , 0.33333334],
       [0.25      , 0.2       , 0.16666667, 0.14285715],
       [0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.08333334, 0.07692308, 0.07142857, 0.06666667]], dtype=float32)

In [84]:
m = np.arange(10)
m1 = np.exp(m)
m1

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [85]:
m2 = np.sqrt(m)
m2

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [86]:
np.maximum(m1,m2)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [87]:
np.minimum(m1,m2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

Obtener los índices:

In [88]:
m = np.random.randint(0,5,15)
m

array([2, 4, 4, 0, 2, 0, 2, 2, 2, 0, 4, 2, 4, 0, 0])

In [90]:
np.where(m==0)

(array([ 3,  5,  9, 13, 14]),)

In [95]:
m2 = np.random.randint(0,5,(5,5))
m2

array([[0, 4, 1, 4, 3],
       [2, 4, 3, 0, 3],
       [1, 0, 3, 2, 4],
       [3, 3, 3, 2, 2],
       [0, 0, 3, 4, 4]])

In [96]:
print(np.where(m2==0))
a,b = np.where(m2==0)
L = list(zip(a,b))
print(L)

(array([0, 1, 2, 4, 4]), array([0, 3, 1, 0, 1]))
[(0, 0), (1, 3), (2, 1), (4, 0), (4, 1)]


In [98]:
L = [1,2,3,4]*4
m = np.array(L).reshape(4,-1)
m

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [100]:
print(m.sum())
print(np.sum(m))

40
40


In [101]:
m.sum(axis=0) # Sumar cols

array([ 4,  8, 12, 16])

In [102]:
m.sum(axis=1) # Sumar filas

array([10, 10, 10, 10])

In [103]:
m.mean()

2.5

In [104]:
m.mean(axis=0)

array([1., 2., 3., 4.])

In [105]:
print(m[0].sum())
print(m[0].mean())

10
2.5
